plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework.boot:spring-boot-autoconfigure:3.3.2'
    api 'io.jsonwebtoken:jjwt-api:0.12.6'
    implementation 'org.springframework.security:spring-security-core:6.3.1'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}